// src/pages/Register.jsx



import toast, { Toaster } from 'react-hot-toast';
import * as Yup from "yup"
import { useFormik } from 'formik';
import FormInput from "../components/Input/FormInput"
import { FiXCircle } from "react-icons/fi";
import { Link, useNavigate } from 'react-router-dom';


const Register = () => {
    //message state

    const navigate = useNavigate();


    const formik = useFormik({
        initialValues: {
            name: '',
            lastname: '',
            email: '',
            password: ''
        },
        validationSchema: Yup.object({
            name: Yup.string().required("Name is mandatory"),
            lastname: Yup.string().required("Lastname is mandatory"),
            email: Yup.string().email('Email is not valid').required("Email is mandatory"),
            password: Yup.string().min(8, 'Password has to be at least 8 characters').required("Password is mandatory"),
        }),
        onSubmit: async values => {
            try {
                console.log(values);

            } catch (error) {
                toast.error(error.message, {
                    style: {
                        border: '1px solid #2c5282',
                        padding: '16px',
                        color: '#2c5282',
                        backgroundColor: "white"
                    },
                });
            }
        }

    })
    const showMessage = () => {
        return (

            <div className={`alert ${message.error ? "alert-danger " : "bg-white"}  py-2 px-3 mx-auto rounded`} >
                <p >
                    {message.msg}
                </p>
            </div >
        )
    }
    const ErrorMessage = ({ message }) => (
        <div className='my-2 alert bg-danger bg-opacity-75'>
            <div className='d-flex align-items-center ' >
                <FiXCircle />
                <p className='fw-bold p-0 m-0 ms-2 '> {message}</p>
            </div>


        </div>
    )
    return (

        <>


            <Toaster
                position="bottom-center"
                reverseOrder={false}
            />
            <div className='d-flex justify-content-center vh-100 '>
                <div className='row align-items-center w-100'>
                    <div className="col-md-6 mx-auto">
                        <h1 className="text-center">
                            Register</h1>

                        <form onSubmit={formik.handleSubmit}>
                            <FormInput
                                htmlForm="fname"
                                placeholder="John"
                                type="text"
                                label="Name"
                                id="name"
                                value={formik.values.name}
                                onChange={formik.handleChange}
                                onBlur={formik.handleBlur}
                            />
                            {formik.errors.name && formik.touched.name ? (
                                <ErrorMessage message={formik.errors.name} />
                            ) : null}
                            <FormInput
                                onBlur={formik.handleBlur}
                                value={formik.values.lastname}
                                onChange={formik.handleChange}

                                htmlForm="lname"
                                placeholder="Doe"
                                type="text"
                                label="Lastname"
                                id="lastname"
                            />
                            {formik.errors.lastname && formik.touched.lastname ? (

                                <ErrorMessage message={formik.errors.lastname} />

                            ) : null}
                            <FormInput
                                onBlur={formik.handleBlur}
                                value={formik.values.email}
                                onChange={formik.handleChange}

                                htmlForm="email"
                                placeholder="email@email.com"
                                type="email"
                                label="Email"
                                id="email"
                            />
                            {formik.errors.email && formik.touched.email ? (
                                <ErrorMessage message={formik.errors.email} />
                            ) : null}
                            <FormInput
                                onBlur={formik.handleBlur}
                                value={formik.values.password}
                                onChange={formik.handleChange}
                                htmlForm="password"
                                placeholder="Enter your password"
                                type="password"
                                label="Password"
                                id="password"
                            />
                            {formik.errors.password && formik.touched.password ? (
                                <ErrorMessage message={formik.errors.password} />
                            ) : null}

                            <div className="d-grid py-3 my-2">
                                <button type="submit"
                                    className="btn btn-outline-primary">
                                    Sign in
                                </button>
                            </div>


                        </form>
                        <div className='flex flex-col justify-center'>
                            <p className='text-white text-center' >Already registered?</p>
                            <div className='text-center mt-6'>
                                <span className='p-2 text-white bg-blue-800 rounded'> <Link to={'/login'}>Login here</Link></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </>
    )
}

export default Register

// resources/js/src/views/pages/auth/register.vue
<script setup>
import { useForm } from "vee-validate";
import { useRouter } from "vue-router";
import { toast } from "vue3-toastify";
import * as Yup from "yup";

import CustomInput from "../../../components/CustomInput.vue";

import useStore from "../../../store/index";
import axios from "axios";

const store = useStore();
const router = useRouter();

const validationSchema = Yup.object().shape({
    name: Yup.string().required("Empty field"),
    email: Yup.string()
        .required("Please enter an email.")
        .email("The format does not match."),
    password: Yup.string()
        .default("")
        .min(8, "At least 8 charaacters")
        .required("Password can not be empty."),
    confirmPassword: Yup.string()
        .oneOf([Yup.ref("password"), null], "Confirm password does not match.")
        .required("Confirm your password")
        .default(""),
});

const { handleSubmit, isSubmitting } = useForm({
    validationSchema: validationSchema,
});

const onSubmit = handleSubmit(async (values) => {
    try {

        const res = await axios.post("api/register", {
            name: values.name,
            email: values.email,
            password: values.password,
            password_confirmation: values.confirmPassword,
        });

        localStorage.setItem("token", res.data.data.access_token);
        store.setUser(res.data.data.user);
        toast.success(res.data.message);
        router.replace({ name: "home" });
    } catch (error) {
        toast.error(
            error.response.data.message ? error.response.data.message : error.message
        );
    }
});
</script>

<template>
    <div class="container vh-100">
        <div class="row h-100 d-flex justify-content-center align-items-center">
            <div class="col-md-8">
                <form @submit="onSubmit">
                    <h1 class="display-6 text-center">Register</h1>
                    <CustomInput type="text" name="name" label="Name" placeholder="Name" />
                    <CustomInput type="email" name="email" label="Email" placeholder="Email" />
                    <CustomInput type="password" name="password" label="Password" placeholder="Password" />
                    <CustomInput type="password" name="confirmPassword" label="Confirm password"
                        placeholder="Confirm password" />

                    <button :disabled="isSubmitting" class="w-100 btn btn-lg btn-primary" type="submit">
                        Register
                    </button>
                </form>
                <div className="flex flex-col justify-center pt-3">
                    <p className="text-center pb-3">Already registered?</p>
                    <div className="text-center mt-6">
                        <span className="p-2 text-white bg-blue-800 rounded">
                            <router-link :to="{ name: 'login' }">Login here</router-link></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<style scoped></style>
